/** @type {import('tailwindcss').Config} */
import plugin from 'tailwindcss/plugin';

export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303030",
        "surface-bright": "#fbf9f8",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#2f1500",
        "surface-container": "#efeded",
        "primary": "#001e40",
        "on-secondary-fixed-variant": "#004c6b",
        "primary-fixed-dim": "#a7c8ff",
        "inverse-primary": "#a7c8ff",
        "on-surface": "#1b1c1c",
        "surface-tint": "#3a5f94",
        "background": "#fbf9f8",
        "secondary-fixed-dim": "#82cfff",
        "surface-container-highest": "#e4e2e2",
        "on-surface-variant": "#43474f",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "secondary-container": "#2dbcfe",
        "secondary-fixed": "#c6e7ff",
        "on-primary-fixed-variant": "#1f477b",
        "primary-container": "#003366",
        "on-primary-fixed": "#001b3c",
        "tertiary-fixed-dim": "#ffb77d",
        "tertiary": "#331700",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#00658d",
        "surface-dim": "#dbd9d9",
        "tertiary-container": "#512900",
        "tertiary-fixed": "#ffdcc3",
        "surface-container-high": "#eae8e7",
        "on-tertiary-fixed-variant": "#6e3900",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f2f0f0",
        "primary-fixed": "#d5e3ff",
        "surface-container-low": "#f5f3f3",
        "on-background": "#1b1c1c",
        "on-primary-container": "#799dd6",
        "on-error-container": "#93000a",
        "on-secondary-container": "#004866",
        "on-tertiary-container": "#ea8000",
        "outline-variant": "#c3c6d1",
        "surface-variant": "#e4e2e2",
        "surface": "#fbf9f8",
        "outline": "#737780",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#001e2d",
        "accent": "#ff8c00",
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "container-max": "1280px",
        "base": "8px"
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "headline-xl-mobile": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "headline-sm": ["Montserrat", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
      },
    },
  },
  plugins: [],
};
